### ISSUE TITLE
[Docs] Wrong markup

### ISSUE THREAD

**Issue by craigengland** [hotwired/stimulus-site#15]
In [this](https://stimulus.hotwired.dev/handbook/designing-for-resilience#progressively-enhancing-the-pin-field) section of the handbook, it appears that the `data-clipboard-supported-class="supported" is added to the button, however in order to get this to work I had to add it to the controller element.

For example:
```
<div data-controller="clipboard" data-clipboard-supported-class="clipboard--supported">
  <input data-clipboard-target="source" type="text" value="1234" readonly />
  <button data-action="clipboard#copy" class="clipboard-button">Copy to Clipboard</button>
</div>
```

Maybe we could add in a small update explaining where this attribute should go?

**Comment by attilagyorffy** [comment]
@craigengland beat me to it! I was going to open a PR too but given that I'm just learning Stimulus, I wasn't sure how to describe the correlation between the static classes and the markup in a reasonably simple way without misinforming users about the inner workings of the framework.

**Comment by ThriceGood** [comment]
This is still the case. It was a little confusing. It actually just says to add class="clipboard-button" to the button element without mentioning to add data-clipboard-supported-class="clipboard--supported" to the outer div. For some reason it seems to be randomly in the button element.

**Comment by marcoroth** [comment]
Looks like this has been fixed in https://github.com/hotwired/stimulus/pull/482
